# Activity 2 Part 2 - Verification the query results from the CSV Files

In [1]:
library(dplyr)
players <- read.csv("players.csv", header= TRUE)
teams <- read.csv("teams.csv", header= TRUE)

Warning message:
"package 'dplyr' was built under R version 3.3.3"
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

### Verification of the player data

In [2]:
players

      X     player_api_id player_name              overall_rating gk_rating
1      1    2625          Patryk Rachwal,18        63             153
2      2    2752          Diego Mainz              72              53
3      3    2768          Jose Dorado              75             128
4      4    2770          Ignacio Gonzalez         74             148
5      5    2790          Alberto Rey              73             144
6      6    2796          Javier Jimenez           69             340
7      7    2802          Pablo Hernandez          82             146
8      8    2805          Ruben Perez              76             141
9      9    2857          Ivan Perez               72             143
10    10    2862          Vicente Sanchez          76             146
11    11    2907          Gregory Lacombe          68             135
12    12    2973          Ugur Inceman             72             147
13    13    2977          David Rivas Rodriguez    82             104
14    14    2983          Jorge Molina             75             139
15    15    2984          Sergio Aragones          75             364
16    16    3140          Alexandre Hauw           69             136
17    17    3204          Marat Izmailov           81             156
18    18    3263          Kelly Berville           67             115
19    19    3264          Abdelmalek Cherrad       62              98
20    20    3316          Oscar Sanchez            71             108
21    21    3329          Vincent Euvrard          64             130
22    22    3377          Luca Belingheri          72             138
23    23    3441          Aleksander Radosavljevic 71             138
24    24    3512          Peter Halmosi            75             143
25    25    3517          Alexandr Kerzhakov       82             149
26    26    3520          Andrey Arshavin          86             159
27    27    4747          Lee Wilkie               73             128
28    28    4863          Boban Grncarov           66              54
29    29    4902          Iriney                   77             145
30    30    4939          Tim Clancy               64             116
...   ...   ...           ...                      ...            ...
11031 11031 701154        Kylian Mbappe Lottin     65             42
11032 11032 703659        Colin Trachsel           51             48
11033 11033 704523        Christopher Nkunku       62             43
11034 11034 705484        Eray Cumart              52             32
11035 11035 706985        Jordan Lyden             58             53
11036 11036 710807        Jonatan Montiel          67             47
11037 11037 715642        Aissa Laidouni           59             61
11038 11038 716998        Sebastien Lamonge        56             46
11039 11039 717248        Felipe Augusto           64             59
11040 11040 717270        Antoine Rabillard        61             56
11041 11041 717557        Levi Garcia              64             49
11042 11042 719413        Dorian Caddy             64             54
11043 11043 720738        Charles Traore           55             52
11044 11044 721133        Rafa Soares              70             60
11045 11045 722766        Charly Musonda           71             36
11046 11046 723037        Wanderson Lima           53             54
11047 11047 725718        Dennis van der Heijden   60             54
11048 11048 726956        Cedric Itten             54             41
11049 11049 728125        Christopher McLaughlin   50             49
11050 11050 728414        Justin Hoogma            59             54
11051 11051 728478        Kamil Jozwiak            56             54
11052 11052 730065        Jorge Intima             57             59
11053 11053 733787        Linus Obexer             51             45
11054 11054 742405        Tom Davies               51             56
11055 11055 743720        Charles Pickel           50             53
11056 11056 744907        Greg Taylor              53             57
11057 11057 746419        Francisco Afonso         59             42
11058 11058 748432        Fynn Arkenberg           58             46
11059 11059 750435        Rees Greenwood           60             48
11060 11060 750584        Alexandre Azevedo        58             54
      appearances league_count
1      90         1
2      81         1
3      71         1
4      16         2
5      50         1
6       1         1
7     144         2
8     131         1
9       3         1
10     17         1
11      6         1
12     16         1
13      5         1
14     71         1
15     38         1
16     42         1
17     42         1
18     19         1
19      1         1
20      6         1
21     85         1
22      1         1
23     74         1
24      4         1
25     17         1
26     70         1
27     36         1
28     25         1
29     68         1
30     97         1
...   ...         ...
11031  2          1
11032  1          1
11033  4          1
11034  4          1
11035  2          1
11036  1          1
11037  1          1
11038  1          1
11039  4          1
11040  1          1
11041  4          1
11042  3          1
11043  5          1
11044 15          1
11045 13          1
11046  7          1
11047  1          1
11048  4          1
11049  2          1
11050  1          1
11051  1          1
11052  1          1
11053  2          1
11054  1          1
11055  1          1
11056  1          1
11057  2          1
11058  2          1
11059  1          1
11060  1          1

### Verification of the Team Data

In [3]:
teams

    X   team_api_id team_long_name               team_short_name goals_scored
1    1  1601        Ruch Chorzów                 CHO             280
2    2  1773        Oud-Heverlee Leuven          O-H             126
3    3  1957        Jagiellonia Bialystok        BIA             287
4    4  2033        S.C. Olhanense               OLH             138
5    5  2182        Lech Poznan                  POZ             372
6    6  2183        P. Warszawa                  PWA             184
7    7  2186        Cracovia                     CKR             235
8    8  4049        Tubize                       TUB              35
9    9  4064        Feirense                     FEI              27
10  10  4087        Évian Thonon Gaillard FC     ETG             180
11  11  4170        US Boulogne Cote D'Opale     BOU              31
12  12  6269        Novara                       NOV              34
13  13  6351        KAS Eupen                    EUP              28
14  14  6367        Uniao da Madeira             MAD              27
15  15  6391        GFC Ajaccio                  GAJ              37
16  16  6403        FC Paços de Ferreira         FER             292
17  17  6413        PEC Zwolle                   ZWO             204
18  18  6421        Leixões SC                   LEI              55
19  19  6433        Go Ahead Eagles              GAE              74
20  20  6493        AC Bellinzona                BEL             128
21  21  6547        FC Penafiel                  PEN              29
22  22  6601        FC Volendam                  VOL              38
23  23  6631        FC Dordrecht                 DOR              24
24  24  7730        FC Lausanne-Sports           LAU              99
25  25  7788        SC Cambuur                   CAM             119
26  26  7794        SC Bastia                    BAS             165
27  27  7819        SM Caen                      CAE             220
28  28  7841        Rio Ave FC                   RA              248
29  29  7842        Estoril Praia                EST             167
30  30  7844        Vitória Guimarães            GUI             300
... ... ...         ...                          ...             ...
270 270  10214      CD Nacional                  NAC             332
271 271  10215      Académica de Coimbra         ACA             240
272 272  10217      ADO Den Haag                 HAA             366
273 273  10218      Excelsior                    EXC             154
274 274  10219      RKC Waalwijk                 RKC             153
275 275  10228      SC Heerenveen                HEE             470
276 276  10229      AZ                           ALK             492
277 277  10233      Genoa                        GEN             392
278 278  10235      Feyenoord                    FEY             489
279 279  10238      Vitória Setúbal              SET             238
280 280  10242      ES Troyes AC                 TRO              71
281 281  10243      FC Zürich                    ZUR             468
282 282  10249      Montpellier Hérault SC       MON             344
283 283  10251      Hibernian                    HIB             259
284 284  10252      Aston Villa                  AVL             335
285 285  10260      Manchester United            MUN             582
286 286  10261      Newcastle United             NEW             324
287 287  10264      SC Braga                     BRA             398
288 288  10265      Wisla Kraków                 WIS             332
289 289  10267      Valencia CF                  VAL             484
290 290  10268      Elche CF                     ELC              65
291 291  10269      VfB Stuttgart                STU             415
292 292  10278      Hércules Club de Fútbol      HER              36
293 293  10281      Real Valladolid              VAL             170
294 294 108893      AC Arles-Avignon             ARL              21
295 295 158085      FC Arouca                    ARO             101
296 296 177361      Termalica Bruk-Bet Nieciecza TBN              33
297 297 188163      Tondela                      TON              34
298 298 208931      Carpi                        CAP              37
299 299 274581      Royal Excel Mouscron         MOP              71
    buildupScore chanceCreationScore defenseScore
1   139          186                 175
2   153          157                 137
3   158          163                 210
4   147          165                 155
5   176          196                 160
6    NA          180                 175
7   125          168                 205
8    NA           NA                  NA
9    NA           NA                  NA
10  156          180                 165
11   NA          165                 200
12  179          172                 151
13   NA          160                 155
14   NA           NA                  NA
15  153          179                 146
16  142          170                 150
17  137          165                 181
18   NA          165                  90
19  160          132                 141
20   NA          175                 150
21  147          146                 121
22   NA           NA                  NA
23  134          176                 164
24  141          164                 165
25  136          159                 138
26  174          156                 210
27  157          165                 205
28  157          180                 153
29  174          139                 150
30  131          179                 177
... ...          ...                 ...
270 167          165                 156
271 150          172                 151
272 162          181                 173
273 163          162                 106
274 142          159                 150
275 150          171                 183
276 154          185                 184
277 184          182                 154
278 154          165                 160
279 149          165                 140
280 148          150                 140
281 157          165                 163
282 162          160                 210
283 148          200                 200
284 170          185                 145
285 134          200                 163
286 152          195                 161
287 145          166                 150
288 135          183                 205
289 116          185                 175
290 171          165                 158
291 168          200                 175
292 154          178                 160
293 153          172                 161
294 156          141                 158
295 174          160                 113
296  NA           NA                  NA
297  NA           NA                  NA
298 190          160                 141
299 150          150                 140

### Top 10 players with the highest overall rating

In [4]:
rtg <- select(players, player_api_id, player_name, overall_rating)
top_n(arrange(rtg, desc(overall_rating)),10)

Selecting by overall_rating

   player_api_id player_name       overall_rating
1  30981         Lionel Messi      94
2  30717         Gianluigi Buffon  93
3  30829         Wayne Rooney      93
4  30893         Cristiano Ronaldo 93
5  39854         Xavi Hernandez    92
6  39989         Gregory Coupet    92
7  30626         Thierry Henry     91
8  30627         John Terry        91
9  30657         Iker Casillas     91
10 30723         Alessandro Nesta  91
11 30743         Ronaldinho        91
12 30955         Andres Iniesta    91
13 34520         Fabio Cannavaro   91

### Top 10 players with the highest goal keeper rating

In [5]:
gk <- select(players, player_api_id, player_name, gk_rating)
top_n(arrange(gk, desc(gk_rating)),10)

Selecting by gk_rating

   player_api_id player_name       gk_rating
1   30717        Gianluigi Buffon  449
2   39989        Gregory Coupet    447
3   30859        Petr Cech         445
4   30657        Iker Casillas     442
5   27299        Manuel Neuer      440
6   30989        Julio Cesar       438
7   24503        Sebastian Frey    437
8   30726        Edwin van der Sar 436
9  182917        David De Gea      429
10  30660        Pepe Reina        428

### Top 10 players with highest appearances

In [6]:
app <- select(players, player_api_id, player_name, appearances)
top_n(arrange(app, desc(appearances)),10)

Selecting by appearances

   player_api_id player_name          appearances
1  31293         Steve Mandanda       300
2  41097         Stephane Ruffier     294
3  33764         Gorka Iraizoz Moreno 286
4  42422         Samir Handanovic     286
5  26295         Hugo Lloris          282
6  31465         Tim Howard           282
7  31432         Joe Hart             275
8  26168         Cedric Carrasso      268
9  26399         Daniel Congre        262
10 94550         Moussa Sissoko       260

### Top 10 players who played in the most number of leagues

In [7]:
lgc <- select(players, player_api_id, player_name, league_count)
top_n(arrange(lgc, desc(league_count)),10)

Selecting by league_count

   player_api_id player_name             league_count
1   42119        Gelson Fernandes        6
2  116750        Ricky van Wolfswinkel   5
3  178538        Filip Djuricic          5
4   22543        Radamel Falcao          4
5   24123        Jonathan De Guzman      4
6   25816        Almen Abdi              4
7   26434        Ibrahim Afellay         4
8   26489        Edson Braafheid         4
9   26675        Eljero Elia             4
10  30477        Danijel Pranjic         4
11  30692        Oguchi Onyewu           4
12  30841        Maarten Stekelenburg    4
13  30890        Philippe Senderos       4
14  30918        David Rozehnal          4
15  31294        Niki Zimling            4
16  31300        Rolando                 4
17  32937        Christian Poulsen       4
18  33074        Eidur Gudjohnsen        4
19  36784        Klaas Jan Huntelaar     4
20  38229        Bryan Ruiz              4
21  38369        Dieumerci Mbokani       4
22  38700        Florent Sinama-Pongolle 4
23  38795        Sebastien Pocognoli     4
24  40004        Hassan Yebda            4
25  40165        Pablo Osvaldo           4
26  41877        Olivier Kapo            4
27  46509        Angel Di Maria          4
28  47547        Emiliano Insua          4
29  71353        Marko Marin             4
30  93484        Aly Cissokho            4
31  96643        Bojan Krkic             4
32 109060        Sergio Romero           4
33 129918        Alfred Finnbogason      4
34 156534        Aleksandar Tonev        4
35 156556        Nelson Oliveira         4
36 163199        Vladimir Weiss          4
37 163205        Gael Kakuta             4
38 170775        Haris Seferovic         4
39 176300        Xherdan Shaqiri         4
40 183548        Stefan Scepovic         4
41 213502        Jose Campana            4
42 242887        Christian Atsu          4

### Top 10 teams with the highest buildup score

In [8]:
bs <- select(teams, team_api_id, team_short_name, team_long_name, buildupScore)
top_n(arrange(bs, desc(buildupScore)),10)

Selecting by buildupScore

   team_api_id team_short_name team_long_name             buildupScore
1    9804      TOR             Torino                     209
2    8600      UDI             Udinese                    205
3    8194      FDU             Fortuna Düsseldorf         198
4    8033      POD             Podbeskidzie Bielsko-Biala 193
5    8245      KKI             Korona Kielce              192
6    8024      WID             Widzew Lódz                190
7    8244      LOD             Widzew Lódz                190
8  208931      CAP             Carpi                      190
9    9830      NAN             FC Nantes                  189
10   7943      SAS             Sassuolo                   188
11   8543      LAZ             Lazio                      188

### Top 10 teams with the highest chance creation score

In [9]:
cs <- select(teams, team_api_id, team_short_name, team_long_name, chanceCreationScore)
top_n(arrange(cs, desc(chanceCreationScore)),10)

Selecting by chanceCreationScore

   team_api_id team_short_name team_long_name          chanceCreationScore
1   8543       LAZ             Lazio                   220
2   8697       WBR             SV Werder Bremen        216
3   9875       NAP             Napoli                  215
4   8178       LEV             Bayer 04 Leverkusen     210
5   8191       BUR             Burnley                 210
6   8344       CAR             Cardiff City            210
7   8456       MCI             Manchester City         210
8   8485       ABE             Aberdeen                210
9   8548       RAN             Rangers                 210
10  8586       TOT             Tottenham Hotspur       210
11  8592       MAR             Olympique de Marseille  210
12  8602       WOL             Wolverhampton Wanderers 210
13  8658       BIR             Birmingham City         210
14  8721       WOL             VfL Wolfsburg           210
15  9798       REA             Reading                 210
16  9800       MIR             St. Mirren              210
17  9860       HEA             Heart of Midlothian     210
18 10003       SWA             Swansea City            210
19 10172       QPR             Queens Park Rangers     210

### Top 10 teams with the highest defense score

In [10]:
ds <- select(teams, team_api_id, team_short_name, team_long_name, defenseScore)
top_n(arrange(ds, desc(defenseScore)),10)

Selecting by defenseScore

   team_api_id team_short_name team_long_name          defenseScore
1   1957       BIA             Jagiellonia Bialystok   210
2   7794       BAS             SC Bastia               210
3   8021       ZAG             Zaglebie Lubin          210
4   8197       LEI             Leicester City          210
5   8344       CAR             Cardiff City            210
6   8350       KAI             1. FC Kaiserslautern    210
7   8466       SOU             Southampton             210
8   8481       NAN             AS Nancy-Lorraine       210
9   8483       BLA             Blackpool               210
10  8521       BRE             Stade Brestois 29       210
11  8602       WOL             Wolverhampton Wanderers 210
12  8658       BIR             Birmingham City         210
13  8659       WBA             West Bromwich Albion    210
14  8667       HUL             Hull City               210
15  8678       BOU             Bournemouth             210
16  9831       NIC             OGC Nice                210
17  9847       PSG             Paris Saint-Germain     210
18  9851       REN             Stade Rennais FC        210
19  9904       HAN             Hannover 96             210
20  9986       CHA             Sporting Charleroi      210
21  9993       BAC             Beerschot AC            210
22 10001       WES             KVC Westerlo            210
23 10003       SWA             Swansea City            210
24 10172       QPR             Queens Park Rangers     210
25 10249       MON             Montpellier Hérault SC  210

### Top 10 highest goal scoring teams in europe

In [11]:
gs <- select(teams, team_api_id, team_short_name, team_long_name, goals_scored)
top_n(arrange(gs, desc(goals_scored)),10)

Selecting by goals_scored

   team_api_id team_short_name team_long_name    goals_scored
1   8634       BAR             FC Barcelona      849
2   8633       REA             Real Madrid CF    843
3   9925       CEL             Celtic            695
4   9823       BMU             FC Bayern Munich  653
5   8640       PSV             PSV               652
6   8593       AJA             Ajax              647
7   9931       BAS             FC Basel          619
8   8456       MCI             Manchester City   606
9   8455       CHE             Chelsea           583
10 10260       MUN             Manchester United 582